### ISSUE TITLE
Gratefulness Counter / Annoyance Counter

### ISSUE THREAD

**Issue by gregoralbrecht** [12m12p/12m12p#1]
# Product Requirements

## Goals & Objectives
It's way harder to keep in mind how often things went well than to remember when they didn't. Being actively aware of moments of happiness or gratefulness improves a person's overall wellbeing. _**Track what pleases/annoys you and how often it does to identify things that make you happy or things you need to improve.**_

## Assumptions
- Identify moments of gratefulness during everyday life
- When you want to improve something in your life you need to figure out what is annoying and what makes you happy.
- People do not realize what is annoying in their every day life unless they track how often sth is annoying/pleasing
- Unveil new opportunities to improve something substantial
- Create tiny quantifiable track records, e.g. _"I didn't miss the bus 412 times last week"_

## User Stories

- [ ] As a user, I want to quickly add habits/ things/ goods/ activities which are annoying/ pleasing so that I can identify ways to be more happy

- [ ] As a user, I want to quickly increment the counter of whether something is pleasing/ annoying so that I can easily track 

- [ ] As a user, I want to see what is the most annoying/ pleasing thing so that I know what I have to do

### Frontend
- Gatsby 
- Progressive Web App
- Social Sign On (Auth0)

### Backend
- AWS App Sync?
- Tracking upvotes and downvotes within a ledger

**Comment by kjhnns** [comment]
# Product Requirements

## Goals & Objectives
Track what pleases/ annoys you and how often it does so to identify things that make you happy  

## Assumptions
- When you want to improve something in your life you need to figure out what is annoying and what makes you happy.
- People do not realize what is annoying in their every day life unless they track how often sth is annoying/pleasing
- Unveil new opportunities to improve something substantial


## User Stories
As a user, I want to quickly add habits/ things/ goods/ activities which are annoying/ pleasing so that I can identify ways to be more happy
As a user, I want to quickly increment the counter of whether something is pleasing/ annoying so that I can easily track 
As a user, I want to see what is the most annoying/ pleasing thing so that I know what I have to do
